runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3.6
  
handlers:
- url: /static
  static_dir: static
  expiration: '10s'
  
env_variables:
    MYSQL_HOST: localhost
    MYSQL_USER: flask
    MYSQL_PASSWORD: Flask_123
    MYSQL_DB: borestook
    SECRET_KEY: 1356d24c50414b44221cbc80ac0bf45a
    MAIL_USERNAME: vuttan1995@gmail.com
    MAIL_PASSWORD: 01664292129
    CLOUD_SQL_INSTANCES: final-thesis-100496:asia-east2:borestook
beta_settings:
    cloud_sql_instances: final-thesis-100496:asia-east2:borestook